In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("customer_shopping_behavior.csv")
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [3]:
df.columns = df.columns.str.lower().str.replace({
    " " : "_",
    "(" : "",
    ")" : ""
})
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_usd', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [4]:
df.isna().sum()

customer_id                0
age                        0
gender                     0
item_purchased             0
category                   0
purchase_amount_usd        0
location                   0
size                       0
color                      0
season                     0
review_rating             37
subscription_status        0
shipping_type              0
discount_applied           0
promo_code_used            0
previous_purchases         0
payment_method             0
frequency_of_purchases     0
dtype: int64

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_id             3900 non-null   int64
 1   age                     3900 non-null   int64
 2   gender                  3900 non-null   str
 3   item_purchased          3900 non-null   str
 4   category                3900 non-null   str
 5   purchase_amount_usd     3900 non-null   int64
 6   location                3900 non-null   str
 7   size                    3900 non-null   str
 8   color                   3900 non-null   str
 9   season                  3900 non-null   str
 10  review_rating           3863 non-null   float64
 11  subscription_status     3900 non-null   str
 12  shipping_type           3900 non-null   str
 13  discount_applied        3900 non-null   str
 14  promo_code_used         3900 non-null   str
 15  previous_purchases      3900 non-null   int64
 16  payment_method          3900 non-null   str
 17  frequency_of_purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [6]:
df["review_rating"] = df["review_rating"].fillna(
    df.groupby("category")["review_rating"].transform("median")
)

In [7]:
df.isna().sum()

customer_id               0
age                       0
gender                    0
item_purchased            0
category                  0
purchase_amount_usd       0
location                  0
size                      0
color                     0
season                    0
review_rating             0
subscription_status       0
shipping_type             0
discount_applied          0
promo_code_used           0
previous_purchases        0
payment_method            0
frequency_of_purchases    0
dtype: int64

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_id             3900 non-null   int64
 1   age                     3900 non-null   int64
 2   gender                  3900 non-null   str
 3   item_purchased          3900 non-null   str
 4   category                3900 non-null   str
 5   purchase_amount_usd     3900 non-null   int64
 6   location                3900 non-null   str
 7   size                    3900 non-null   str
 8   color                   3900 non-null   str
 9   season                  3900 non-null   str
 10  review_rating           3900 non-null   float64
 11  subscription_status     3900 non-null   str
 12  shipping_type           3900 non-null   str
 13  discount_applied        3900 non-null   str
 14  promo_code_used         3900 non-null   str
 15  previous_purchases      3900 non-null   int64
 16  payment_method          3900 non-null   str
 17  frequency_of_purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [9]:
labels = ["Young Adult", "Adult", "Middle-Aged", "Senior"]
df['age_group'] = pd.qcut(df['age'], q=4, labels= labels)
df['age_group']

0       Middle-Aged
1       Young Adult
2       Middle-Aged
3       Young Adult
4       Middle-Aged
           ...
3895          Adult
3896    Middle-Aged
3897    Middle-Aged
3898          Adult
3899    Middle-Aged
Name: age_group, Length: 3900, dtype: category
Categories (4, str): ['Young Adult' < 'Adult' < 'Middle-Aged' < 'Senior']

In [10]:
df['frequency_of_purchases'].unique().sum()

'FortnightlyWeeklyAnnuallyQuarterlyBi-WeeklyMonthlyEvery 3 Months'

In [11]:
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}
df['frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [12]:
df[ ['frequency_days', 'frequency_of_purchases']]

      frequency_days frequency_of_purchases
0                 14            Fortnightly
1                 14            Fortnightly
2                  7                 Weekly
3                  7                 Weekly
4                365               Annually
...              ...                    ...
3895               7                 Weekly
3896              14              Bi-Weekly
3897              90              Quarterly
3898               7                 Weekly
3899              90              Quarterly

[3900 rows x 2 columns]

In [14]:
df.to_csv("customer_data2.csv", index=False)